// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZeJbLcwAgbOZfl2ICLQejKiu1_f-Xk0',
    appId: '1:243342109546:web:39dbd109f0fcaecdf15313',
    messagingSenderId: '243342109546',
    projectId: 'safecar-fca02',
    authDomain: 'safecar-fca02.firebaseapp.com',
    storageBucket: 'safecar-fca02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxzP7d7GpAdps7vtrLla7hTahdQLD4zAw',
    appId: '1:243342109546:android:4f8639fc1f6f3205f15313',
    messagingSenderId: '243342109546',
    projectId: 'safecar-fca02',
    storageBucket: 'safecar-fca02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbFVAINn2EOSmO4Q6g6JfOE352CDS9h8',
    appId: '1:243342109546:ios:33112f26d143c19af15313',
    messagingSenderId: '243342109546',
    projectId: 'safecar-fca02',
    storageBucket: 'safecar-fca02.firebasestorage.app',
    iosBundleId: 'com.example.piloto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgbFVAINn2EOSmO4Q6g6JfOE352CDS9h8',
    appId: '1:243342109546:ios:33112f26d143c19af15313',
    messagingSenderId: '243342109546',
    projectId: 'safecar-fca02',
    storageBucket: 'safecar-fca02.firebasestorage.app',
    iosBundleId: 'com.example.piloto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmZeJbLcwAgbOZfl2ICLQejKiu1_f-Xk0',
    appId: '1:243342109546:web:07605cf7ffb8e0a9f15313',
    messagingSenderId: '243342109546',
    projectId: 'safecar-fca02',
    authDomain: 'safecar-fca02.firebaseapp.com',
    storageBucket: 'safecar-fca02.firebasestorage.app',
  );

}